name: project_akhir_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fl_chart: ^0.64.0
  http: ^1.4.0
  midtrans_sdk: ^1.0.0
  url_launcher: ^6.3.1
  webview_flutter: ^4.11.0
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  midtrans_snap: ^1.0.1
  webview_flutter_android: ^4.4.2
  webview_flutter_platform_interface: ^2.11.0
  iamport_webview_flutter: ^3.1.0
  # device_preview: ^1.2.0
  flutter_dotenv: ^5.2.1
  youtube_player_flutter: ^9.1.1
  url_strategy: ^0.3.0
  flutter_stripe: ^11.5.0
  go_router: ^15.1.2
  intl: ^0.19.0
  # uni_links: ^0.5.1

flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - asset/image/
    - asset/icon/
    - asset/images/
dev_dependencies:
  flutter_lints: ^5.0.0
    
